### PR TITLE
Modernize plugin

### PR DESCRIPTION
**Pull request by basil**

### CODE REVIEW

**Comment by basil** [comment]
Used my admin powers to replay the build with the `Jenkinsfile` changes here: https://ci.jenkins.io/job/Plugins/job/structs-plugin/job/PR-167/2/

**Review by car-roll — APPROVED** [review]

**Comment by car-roll** [comment]
@basil does this need to be released?

**Comment by basil** [comment]
I can't recall what I was doing at the time I filed this PR and whether or not it needed a release, but a release couldn't hurt I think.

**Comment by tumaf33** [comment]
hi @basil - this PR/release have impacted our Jenkins that was running with old version (Jenkins 2.235).
After a service restart for Jenkins, struct plugin plugin couldn't run and as a result pipelines plugin, credentials plugin and others couldn't be loaded and this is impacted our whole system.

Here is the relevant snippet you would like to see:
```
 Failed Loading plugin Structs Plugin v325.vcb_307d2a_2782 (structs)
java.io.IOException: Failed to load: Structs Plugin (325.vcb_307d2a_2782)
 - Jenkins (2.361.4) or higher required

```
If some people is still using the old version, it will impact them.

**Pull request merged**
