### PR TITLE
[FIXED JENKINS-35918] - Integrate the release 1.1.1 branch

### PR DESCRIPTION
**Pull request by oleg-nenashev**
We needed an urgent fix of https://issues.jenkins-ci.org/browse/JENKINS-35918 , because it was impacting Jenkins 2 installation flow.

CC @daniel-beck @kohsuke

### CODE REVIEW

**Comment by StephenDrewLDS** [comment]
Hey
How can I get this to work on my Jenkins 2.9 install I did this morning?
Cheers,
Steve

**Comment by oleg-nenashev** [comment]
@StephenDrewLDS It should take some time to propagate changes to all Jenkins mirrors. maybe several hours. I suppose there will be an announcement when @rtyler wakes up.

**Comment by StephenDrewLDS** [comment]
OK, thanks.

**Comment by jglick** [comment]
:bee:

**Pull request merged**
