### PR TITLE
Add `gitHubRepo`

### PR DESCRIPTION
**Pull request by basil**

### CODE REVIEW

**Comment by car-roll** [comment]
@basil does this require another release?

**Review by car-roll — APPROVED** [review]

**Comment by basil** [comment]
Yes, PCT can't do the checkout without a valid SCM URL. Sorry for the trouble. Clearly POM editing fatigue is starting to set in.

**Comment by basil** [comment]
Apparently the release didn't happen.

**Comment by car-roll** [comment]
strange 🤔, well i manually kicked it off now

**Pull request merged**
